/* Generated by Cython 0.29.23 */

#ifndef __PYX_HAVE__cy_simulator
#define __PYX_HAVE__cy_simulator

#include "Python.h"

#ifndef __PYX_HAVE_API__cy_simulator

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C double AU;

#endif /* !__PYX_HAVE_API__cy_simulator */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initcy_simulator(void);
#else
PyMODINIT_FUNC PyInit_cy_simulator(void);
#endif

#endif /* !__PYX_HAVE__cy_simulator */
